version: '3'
services:
  postgres:
    image: postgres:13.2-alpine
    networks:
      - awesome
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: name
      POSTGRES_PASSWORD: password

  mongo:
    image: mongo
    networks:
      - awesome
    ports:
      - '27017:27017'
    volumes:
      - data-volume:/data/db

networks:
  awesome:
    driver: bridge

volumes:
  data-volume:
