version: "3"
services:
  postgres:
    container_name: "sanfranoid_db"
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: name
      POSTGRES_PASSWORD: password
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
