export const THEME_CHANGE = `THEME/THEME_CHANGE`
export const REQUEST_THEME = `THEME/REQUEST_THEME`
export const SET_STATUS = `THEME/SET_STATUS`
export const REGISTRATION_USER = `THEME/REGISTRATION_USER`

