export const FORUM_GET_FORUMS = `FORUM/GET_FORUMS`
export const FORUM_SET_FORUMS = `FORUM/SET_FORUMS`

export const FORUM_GET_FORUM = `FORUM/GET_FORUM`
export const FORUM_SET_FORUM = `FORUM/SET_FORUM`

export const FORUM_SET_STATUS = `FORUM/SET_STATUS`

export const FORUM_GET_TOPIC = `FORUM/GET_TOPIC`
export const FORUM_SET_TOPIC = `FORUM/SET_TOPIC`

export const FORUM_CREATE_TOPIC = `FORUM/CREATE_TOPIC`
export const FORUM_CREATE_MESSAGES = `FORUM/CREATE_MESSAGES`

export const FORUM_UPDATE_MESSAGES = `FORUM/UPDATE_MESSAGES`
