export { default as AuthPage } from './AuthPage'
export { default as ErrorPage } from './ErrorPage'
export { default as ForumPage } from './ForumPage'
export { default as LeaderBordPage } from './LeaderBordPage'
export { default as Page } from './Page'
export { default as ProfilePage } from './ProfilePage'
export { default as RegistrationPage } from './RegistrationPage'
