export const USER_DATA = `USER/DATA`
export const USER_REQUEST = `USER/REQUEST`
export const USER_SUCCESS = `USER/SUCCESS`
export const USER_SET_STATUS = `USER/SET_STATUS`
export const USER_UPDATE_PROFILE = `USER/UPDATE_PROFILE`
export const USER_UPDATE_AVATAR = `USER/UPDATE_AVATAR`
