const USER_DATA = `USER/DATA`
const USER_REQUEST = `USER/REQUEST`
const USER_SUCCESS = `USER/SUCCESS`
const USER_SET_STATUS = `USER/SET_STATUS`
const USER_UPDATE_PROFILE = `USER/UPDATE_PROFILE`
const USER_UPDATE_AVATAR = `USER/UPDATE_AVATAR`

export {
  USER_DATA,
  USER_REQUEST,
  USER_SUCCESS,
  USER_SET_STATUS,
  USER_UPDATE_PROFILE,
  USER_UPDATE_AVATAR,
}
