export { default } from './classNames'
export { default as toggleFullScreen } from './toggleFullScreen'
export { default as imgErrorConsole } from './imgErrorConsole'
export { setStorage } from './localStorage'
export { getStorage } from './localStorage'
