export const AUTH_SET_AUTH = `AUTH/SET_AUTH`
export const AUTH_LOGIN = `AUTH/LOGIN`
export const AUTH_SET_STATUS = `AUTH/SET_STATUS`
export const AUTH_REGISTRATION = `AUTH/REGISTRATION`
export const AUTH_LOGOUT = `AUTH/LOGOUT`
export const AUTH_LOGIN_OAUTH = 'AUTH/LOGIN/OAUTH'
