const AUTH_SET_AUTH = `AUTH/SET_AUTH`
const AUTH_LOGIN = `AUTH/LOGIN`
const AUTH_SET_STATUS = `AUTH/SET_STATUS`
const AUTH_REGISTRATION = `AUTH/REGISTRATION`
const AUTH_LOGOUT = `AUTH/LOGOUT`

export {
  AUTH_SET_AUTH,
  AUTH_LOGIN,
  AUTH_REGISTRATION,
  AUTH_SET_STATUS,
  AUTH_LOGOUT,
}
