export const LEADERBOARD_SET = 'LEADERBOARD/SET'
export const LEADERBOARD_NEW = 'LEADERBOARD/NEW'
export const LEADERBOARD_REQUEST = 'LEADERBOARD/REQUEST'
export const LEADERBOARD_SET_ISLOADING = 'LEADERBOARD/SET/ISLOADING'
